services:
  nginx-proxy:
    container_name: nginx-proxy
    image: ghcr.io/devops-from-root/nginx-proxy
    #image: nginx-proxy
    #build:
      #context: https://github.com/devops-from-root/nginx-proxy.git
      #context: .
      #dockerfile: Dockerfile
      #args:
        #- BUILD_OPTIONS=--no-cache
    ports:
      - "443:443"
    environment:
      - BACK_URI=${BACK_URI:-localhost}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-zv", "localhost", "443"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 90s
